name: matrix-example
on: push
jobs: 
  build: 
    strategy: 
      matrix: 
        operating-systems: [ubuntu-latest, windows-latest]
        node-versions: [14, 16]
        include: 
          - node-versions: 18
            operating-systems: ubuntu-latest
    runs-on: ${{ matrix.operating-systems}}
    steps: 
      - name: build
        uses: actions/checkout@v3
      - name: node-installation
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-versions }}
          